name: Meteo Casarano

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installa requests
        run: pip install requests

      - name: Leggi ThingSpeak
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python meteo.py

      - name: Salva stato report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet ultimo_report.txt; then
            echo "Nessun nuovo stato report da salvare."
          else
            git add ultimo_report.txt
            git commit -m "Aggiorna stato report orario"
            git push
          fi
